In [1]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

In [2]:
import numpy as np

# Create a Python list
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array
array_list = np.array([1, 2, 3, 4, 5])

# Print data types of both variables
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [4]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and
#arra_list.


In [5]:
import numpy as np

# Create a Python list
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array
array_list = np.array([1, 2, 3, 4, 5])

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(f"Element: {element}, Data type: {type(element)}")

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(f"Element: {element}, Data type: {type(element)}")


Data types of elements in list_:
Element: 1, Data type: <class 'int'>
Element: 2, Data type: <class 'int'>
Element: 3, Data type: <class 'int'>
Element: 4, Data type: <class 'int'>
Element: 5, Data type: <class 'int'>

Data types of elements in array_list:
Element: 1, Data type: <class 'numpy.int32'>
Element: 2, Data type: <class 'numpy.int32'>
Element: 3, Data type: <class 'numpy.int32'>
Element: 4, Data type: <class 'numpy.int32'>
Element: 5, Data type: <class 'numpy.int32'>


In [7]:
#Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)

In [8]:
import numpy as np

# Create a Python list
list_ = [1.5, 2.3, 3.8, 4.1, 5.7]

# Create a NumPy array from list_, with dtype set to int
array_list = np.array(object=list_, dtype=int)

# Print the original list
print("Original list_ elements and their types:")
for element in list_:
    print(f"Element: {element}, Data type: {type(element)}")

# Print data type of each element in array_list after the dtype change
print("\narray_list elements after converting to dtype=int:")
for element in array_list:
    print(f"Element: {element}, Data type: {type(element)}")


Original list_ elements and their types:
Element: 1.5, Data type: <class 'float'>
Element: 2.3, Data type: <class 'float'>
Element: 3.8, Data type: <class 'float'>
Element: 4.1, Data type: <class 'float'>
Element: 5.7, Data type: <class 'float'>

array_list elements after converting to dtype=int:
Element: 1, Data type: <class 'numpy.int32'>
Element: 2, Data type: <class 'numpy.int32'>
Element: 3, Data type: <class 'numpy.int32'>
Element: 4, Data type: <class 'numpy.int32'>
Element: 5, Data type: <class 'numpy.int32'>


In [9]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [10]:
import numpy as np

# Example num_array
num_array = np.array([[1, 2, 3], [4, 5, 6]])

# Find and print the shape of num_array
print(f"Shape of num_array: {num_array.shape}")

# Find and print the size of num_array
print(f"Size of num_array: {num_array.size}")


Shape of num_array: (2, 3)
Size of num_array: 6


In [11]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

# Print the zero matrix
print("3x3 Zero Matrix:")
print(zero_matrix)


3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Print the identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
